#
# This file contains configuration variables for drivers.
# It was generated by genhdrs.pl. Do not modify it.
#
package Driverhdrs;

$LAB = "datalab";
$SERVER_NAME = "scofield.cs.wwu.edu";
$SERVER_PORT = 24702;
$COURSE_NAME = "csapp";
$AUTOGRADE_TIMEOUT = 0;
1;
